services:
  frontend:
    image: fortune-frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
    depends_on: 
      - backend
  backend:
    image: fortune-backend
    ports:
      - "9000:9000"
    environment:
      - REDIS_DNS=db
  db:
    image: redis:latest
    ports:
      - "6379:6379"