name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push frontend
      run: |
        docker build -t ***/fortune-frontend:latest -f frontend/Dockerfile .
        docker push njako21/fortune-frontend:latest

    - name: Build and push backend
      run: |
        docker build -t njako21/fortune-backend:latest -f backend/Dockerfile .
        docker push njako21/fortune-backend:latest
