name: Deploy & Test

on:
  push:
    branches:
      - main
      - deployment-config

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Pull Docker images
      run: |
        docker pull njako21/fortune-frontend:latest
        docker pull njako21/fortune-backend:latest

    - name: Wait for services to start
      run: sleep 20

    - name: Deploy Test
      run: |
        docker compose up -d

    - name: Wait for services to start
      run: sleep 20

    - name: Test frontend application
      run: |
        chmod +x test-app.sh
        ./test-app.sh
   
    - name: Cleanup Deployment
      run: |
        docker compose down
