name: Deploy & Test

on:
  push:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Test
      run: |
        docker-compose up -d

    - name: Wait for services to start
      run: sleep 20

    - name: Test frontend application
      run: |
        chmod +x test-app.sh
        ./test-app.sh http://localhost:8080/
   

    - name: Cleanup Deployment - Frontend
      run: |
        docker-compose down